services:
  app:
    build: .
    container_name: kurikulum_app
    ports:
      - "8282:80"
    volumes:
      - .:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db

  db:
    image: mysql:8.0.40
    container_name: kurikulum_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbkurikulum
      MYSQL_USER: kurikulum
      MYSQL_PASSWORD: kurikulum123
      TZ: Asia/Jakarta
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: kurikulum_phpmyadmin
    ports:
      - "8283:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      TZ: Asia/Jakarta
    depends_on:
      - db

volumes:
  dbdata:
